- name: Add record for JG-DC1
  effectivelywild.technitium_dns.technitium_dns_add_record:
        api_url: "{{ technitium_api_url_2 }}"
        api_token: "{{ technitium_api_token_2 }}"
        api_port: "{{ technitium_api_port_1 }}"
        name: "jg-dc1.jg.net.au"
        type: "A"
        ipAddress: "10.0.40.10"
        ptr: true
        createPtrZone: true 
        ttl: 3600
        validate_certs: 'false'


- name: Add record for JG-DC2
  effectivelywild.technitium_dns.technitium_dns_add_record:
        api_url: "{{ technitium_api_url_2 }}"
        api_token: "{{ technitium_api_token_2 }}"
        api_port: "{{ technitium_api_port_1 }}"
        name: "jg-dc2.jg.net.au"
        type: "A"
        ipAddress: "10.0.40.11"
        ptr: true
        createPtrZone: true 
        ttl: 3600
        validate_certs: 'false'

- name: Add record for JG-SVR1
  effectivelywild.technitium_dns.technitium_dns_add_record:
        api_url: "{{ technitium_api_url_2 }}"
        api_token: "{{ technitium_api_token_2 }}"
        api_port: "{{ technitium_api_port_1 }}"
        name: "jg-svr1.jg.net.au"
        type: "A"
        ipAddress: "10.0.40.5"
        ptr: true
        createPtrZone: true 
        ttl: 3600
        validate_certs: 'false'
